### ISSUE TITLE
AssertionError: Samples in split doesn't match samples in predictions.

### ISSUE THREAD

**Issue by taylorlulu** [neeharperi/FutureDet#11]
Traceback (most recent call last):
  File "/home/lu/Workspace/FutureDet/tools/dist_test.py", line 270, in <module>
    main()
  File "/home/lu/Workspace/FutureDet/tools/dist_test.py", line 260, in main
    association_oracle=args.association_oracle, postprocess=args.postprocess, nogroup=args.nogroup)
  File "/home/lu/Workspace/FutureDet/det3d/datasets/nuscenes/nuscenes.py", line 838, in evaluation
    nogroup=nogroup
  File "/home/lu/Workspace/FutureDet/det3d/datasets/nuscenes/nusc_common.py", line 686, in eval_main
    nogroup=nogroup
  File "/home/lu/anaconda3/envs/futuredet/lib/python3.7/site-packages/nuscenes/eval/detection/evaluate.py", line 225, in __init__
    set(self.gt_boxes.sample_tokens))
AssertionError: Samples in split doesn't match samples in predictions.
As I the debug result shows the length of self.pred_boxes.sample_tokens is 404 doesn't match the length of self.gt_boxes.sample_tokens which is 81.

I was using the v1.0-mini dataaset, and I've changed the param in dist_test.py:
`parser.add_argument("--split", default="mini_val")
parser.add_argument("--version", default="v1.0-mini")
parser.add_argument("--modelCheckPoint", default="latest")`

This issue was is attributed to the inability to access the “val” dataset.
In the v1.0-mini dataset there are 323 training data samples and 81 testing data samples.
As I debug in the 
`if args.testset:
        print("Use Test Set")
        dataset = build_dataset(cfg.data.test)
    else:
        if args.split == "val" or args.split == "mini_val":
            print("Use Val Set")
            dataset = build_dataset(cfg.data.val)
        else:
            print("Use Train Set")
            cfg.data.val.info_path = cfg.data.val.info_path.replace("infos_val_%dsweeps_withvelo_filter_True"%(cfg.data.val.nsweeps), "infos_train_%dsweeps_withvelo_filter_True"%(cfg.data.val.nsweeps))
            cfg.data.val.ann_file = cfg.data.val.info_path.replace("infos_val_%dsweeps_withvelo_filter_True"%(cfg.data.val.nsweeps), "infos_train_%dsweeps_withvelo_filter_True"%(cfg.data.val.nsweeps))
            dataset = build_dataset(cfg.data.val)`
However the output of the dataset.flag.shape is still 323 when I set the '--split' as "mini_val"
![错误1](https://github.com/neeharperi/FutureDet/assets/49311079/8f535fff-1bd7-4c48-abaf-bd0074714269)
![错误2](https://github.com/neeharperi/FutureDet/assets/49311079/578e96ba-5449-4fd0-aaeb-bab4be56e68c)
When the  '--split' as "mini_train" is has the same output  dataset.flag.shape = 323.
The result of dataset.flag.shape is supposed 81.
It seems that the cfg.data.val.info_path and cfg.data.ann_file dosen't work.
I can't figure out what could cause the problem, I'll thanks a lot if you can help.

**Comment by taylorlulu** [comment]
I find the problem the issue is caused by incorrectly setting the info_path parameter.
