### ISSUE TITLE
Problems with training

### ISSUE THREAD

**Issue by mengqingyu123** [neeharperi/FutureDet#4]
Thank you so much for your good open-source work. According to your process, I installed the relevant libraries and trained, but the error is reported as follows:

python train.py --experiment FutureDetection --model forecast_n3dtf
/environment/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
nuScenes devkit not found!
no apex
No Tensorflow
No APEX!
2022-06-26 15:16:58,755 - INFO - Distributed training: False
2022-06-26 15:16:58,755 - INFO - torch.backends.cudnn.benchmark: False
2022-06-26 15:16:58,839 - INFO - Finish RPN Initialization
2022-06-26 15:16:58,840 - INFO - num_classes: [1]
Use HM Bias:  -2.19
2022-06-26 15:16:58,902 - INFO - Finish CenterHead Initialization
Traceback (most recent call last):
  File "./tools/train.py", line 140, in <module>
    main()
  File "./tools/train.py", line 115, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/featurize/work/futuredet/FutureDet/det3d/datasets/builder.py", line 41, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/featurize/work/futuredet/FutureDet/det3d/utils/registry.py", line 78, in build_from_cfg
    return obj_cls(**args)
  File "/home/featurize/work/futuredet/FutureDet/det3d/datasets/nuscenes/nuscenes.py", line 528, in __init__
    root_path, info_path, pipeline, test_mode=test_mode, class_names=class_names
  File "/home/featurize/work/futuredet/FutureDet/det3d/datasets/custom.py", line 37, in __init__
    self._set_group_flag()
  File "/home/featurize/work/futuredet/FutureDet/det3d/datasets/custom.py", line 164, in _set_group_flag
    self.flag = np.ones(len(self), dtype=np.uint8)
  File "/home/featurize/work/futuredet/FutureDet/det3d/datasets/nuscenes/nuscenes.py", line 602, in __len__
    self.load_infos(self._info_path)
  File "/home/featurize/work/futuredet/FutureDet/det3d/datasets/nuscenes/nuscenes.py", line 576, in load_infos
    ratios = [frac / v for v in _cls_dist.values()]
  File "/home/featurize/work/futuredet/FutureDet/det3d/datasets/nuscenes/nuscenes.py", line 576, in <listcomp>
    ratios = [frac / v for v in _cls_dist.values()]
ZeroDivisionError: float division by zero
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 33612) of binary: /environment/miniconda3/bin/python
Traceback (most recent call last):
  File "/environment/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/environment/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-06-26_15:17:04
  host      : featurize
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 33612)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

Can you give me some suggestions? Thank you very much!

**Comment by mengqingyu123** [comment]
The problem seems to be here, "ZeroDivisionError: float division by zero". But I trained according to the source code, and it stands to reason that such a problem should not occur. I used cuda11.2, python3.7, and pytorch1.10.

**Comment by neeharperi** [comment]
Based on your output logs, it seems to me that the setup script did not properly compile all the right dependencies. For example, nuScenes devkit not found indicates that you didn't modify the devkit path. APEX not installed also tells me that APEX didn't compile properly. I'd suggest trying to setup your conda environment with the recommended cuda/cudnn/pytorch environments. The ZeroDivisonError is a red herring. Once you generate the training pkl files after installing all dependencies properly, this should go away.

**Comment by neeharperi** [comment]
Closing due to no followup. If you have a similar issue, please feel free to reopen this thread.
