### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by taylorlulu** [neeharperi/FutureDet#9]
It reported the following error：
Traceback (most recent call last):
  File "./tools/train.py", line 143, in <module>
    main()
  File "./tools/train.py", line 138, in main
    logger=logger,
  File "/home/lu/Workspace/FutureDet/det3d/torchie/apis/train.py", line 358, in train_detector
    trainer.run(data_loaders, cfg.workflow, cfg.total_epochs, cfg=cfg, local_rank=cfg.local_rank)
  File "/home/lu/Workspace/FutureDet/det3d/torchie/trainer/trainer.py", line 584, in run
    epoch_runner(data_loaders[i], self.epoch, **kwargs)
  File "/home/lu/Workspace/FutureDet/det3d/torchie/trainer/trainer.py", line 450, in train
    self.model, data_batch, train_mode=True, **kwargs
  File "/home/lu/Workspace/FutureDet/det3d/torchie/trainer/trainer.py", line 392, in batch_processor_inline
    losses = model(example, return_loss=True)
  File "/home/lu/anaconda3/envs/futuredet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lu/Workspace/FutureDet/det3d/models/detectors/voxelnet.py", line 50, in forward
    x, _ = self.extract_feat(data)
  File "/home/lu/Workspace/FutureDet/det3d/models/detectors/voxelnet.py", line 29, in extract_feat
    x = self.neck(x)
  File "/home/lu/anaconda3/envs/futuredet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lu/Workspace/FutureDet/det3d/models/necks/rpn.py", line 153, in forward
    x = self.blocks[i](x)
  File "/home/lu/anaconda3/envs/futuredet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lu/Workspace/FutureDet/det3d/models/utils/misc.py", line 95, in forward
    input = module(input)
  File "/home/lu/anaconda3/envs/futuredet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lu/anaconda3/envs/futuredet/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/lu/anaconda3/envs/futuredet/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 7.77 GiB total capacity; 1.52 GiB already allocated; 34.38 MiB free; 1.55 GiB reserved in total by PyTorch)
My GPU model is RTX 3070，how to fix this problem or where should I adjust the batch size in the code?
![nvidia_smi截图](https://github.com/neeharperi/FutureDet/assets/49311079/e9501a5c-345a-4023-8fef-1a97a33850d8)

**Comment by neeharperi** [comment]
Hi @taylorlulu, 
You might not be able to train the model as is on 8 GB GPU memory. We set the batch size [here](https://github.com/neeharperi/FutureDet/blob/960115e2d11e40c569c4fb9abc1f0e066e4a07b1/configs/centerpoint/nusc_centerpoint_forecast_n3dtfm_detection.py#L192), but it is already at batch size 1 by default. Another option is to increase the voxel_size to 0.1 or 0.2 [here](https://github.com/neeharperi/FutureDet/blob/960115e2d11e40c569c4fb9abc1f0e066e4a07b1/configs/centerpoint/nusc_centerpoint_forecast_n3dtfm_detection.py#L101) and [here](https://github.com/neeharperi/FutureDet/blob/960115e2d11e40c569c4fb9abc1f0e066e4a07b1/configs/centerpoint/nusc_centerpoint_forecast_n3dtfm_detection.py#L162).

**Comment by taylorlulu** [comment]
Got it, thank you.
